### ISSUE TITLE
Form fields aren't adjusting to one line on large screens. 

### ISSUE THREAD

**Issue by sent0007** [sent0007/registration-form#1]
The Age field and Physical fitness field aren't adjusting at the 60em media query. They shrink to half (unit unit-l-1-2) but stay stacked. It works on Firefox but not on chrome or Markbot. I've tried flexbox and nth children, and changing the display but can't seem to get it working. Any ideas ? 

Thanks @muxlowc

https://github.com/sent0007/registration-form/blob/e6840eced595f25835273382bf5bc6f6bb2a8047/index.html#L23-L44

https://github.com/sent0007/registration-form/blob/e6840eced595f25835273382bf5bc6f6bb2a8047/css/main.css#L14-L26

**Comment by muxlowc** [comment]
@sent0007  you're super close - you just need to move your grid class down a bit like this:

```
<fieldset class="push-0">
        <legend class="unit italic giga push">Personal details</legend>
        <div class="grid">
        <div class="pad-right push unit unit-xs-1 unit-s-1 unit-m-1 unit-l-1-2 unit-xl-1-2">
```
So i just moved your grid down to a new div, and added a "push-0" class on the fieldset

**Comment by sent0007** [comment]
Awesome, yes using another div make sense. Thanks for the help! You mentioned in class that the form won't submit because of updates on formsprees's end. As it stands everything is passing now other than the form submission. Does this meet your requirements for the assignment?  @muxlowc

**Comment by muxlowc** [comment]
@sent0007 you should still be able to submit to markbot - where you have method="POST" make sure that POST is in all capital letters
